FROM postgres:17-alpine

# Add requirements packages
RUN apk update
RUN apk add bash curl git nano

# Add ru_RU locale
RUN apk add tzdata
ENV TZ=Europe/Moscow
ENV LANG=ru_RU.UTF-8
ENV LANGUAGE=ru_RU.UTF-8
ENV LC_ALL=ru_RU.UTF-8

# Set timezone
RUN cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime
RUN echo "Europe/Moscow" > /etc/timezone

# Add locale initdb
ENV POSTGRES_INITDB_ARGS="--locale-provider=icu --icu-locale=ru-RU"

